<html>
<head>
<title>:bist-du-bloe.de</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="css/style.css" type="text/css">
</head>

<body bgcolor="#FEFEFE" text="#000000" link="#999999" vlink="#999999" alink="#999999" leftmargin="0" topmargin="0" rightmargin="0" marginwidth="0" marginheight="0">
<table width="100%" border="0" cellspacing="0" cellpadding="0" height="100%">
  <tr> 
  
    <td rowspan="3" width="200">&nbsp; </td>
 
    <td rowspan="3" width="13" bgcolor="#DBDBDB">&nbsp;</td>

<td height="251">

<TABLE WIDTH=501 BORDER=0 CELLPADDING=0 CELLSPACING=0>
  <TR>
    <TD COLSPAN=3> <a href="http://disturbed-reality.de/v10/index.php?left=content/news.php&right=content/blog.php"><IMG SRC="Bilder/theme_10.3_01.gif" ALT="" WIDTH=501 HEIGHT=25 border="0"></a></TD>
  </TR>
  <TR>
    <TD> <a href="index-brainfuck.php?artcat=3"><IMG SRC="Bilder/theme_10.3_02.gif" ALT="" WIDTH=152 HEIGHT=17 border="0"></a></TD>
    <TD> <a href="http://disturbed-reality.de/board/"><IMG SRC="Bilder/theme_10.3_03.gif" ALT="" WIDTH=168 HEIGHT=17 border="0"></a></TD>
    <TD> <a href="index.php?left=content/neu-zamonien.html&right=content/neu-zamonien2.html"><IMG SRC="Bilder/theme_10.3_04.gif" ALT="" WIDTH=181 HEIGHT=17 border="0"></a></TD>
  </TR>
  <TR>
    <TD> <a href="index.php?left=content/freunde.html&right=content/blank.html"><IMG SRC="Bilder/theme_10.3_05.gif" ALT="" WIDTH=152 HEIGHT=14 border="0"></a></TD>
    <TD> <a href="index.php?left=content/fotos.html&right=content/blank.html"><IMG SRC="Bilder/theme_10.3_06.gif" ALT="" WIDTH=168 HEIGHT=14 border="0"></a></TD>
    <TD> <a href="index.php?left=content/ich.html&right=content/ich2.html"><IMG SRC="Bilder/theme_10.3_07.gif" ALT="" WIDTH=181 HEIGHT=14 border="0"></a></TD>
  </TR>
  <TR>
    <TD> <a href="index.php?left=content/fuss.html&right=content/blank.html"><IMG SRC="Bilder/theme_10.3_08.gif" ALT="" WIDTH=152 HEIGHT=14 border="0"></a></TD>
    <TD> <a href="#" onClick="javascript: window.open('../box/viewshoutbox.php','shoutbox','width=180,height=450,scrollbars=yes');"><IMG SRC="Bilder/theme_10.3_09.gif" ALT="" WIDTH=168 HEIGHT=14 border="0"></a></TD>
    <TD> <a href="index.php?left=content/netzwelten.html&right=content/blank.html"><IMG SRC="Bilder/theme_10.3_10.gif" ALT="" WIDTH=181 HEIGHT=14 border="0"></a></TD>
  </TR>
  <TR>
    <TD COLSPAN=3> <IMG SRC="Bilder/theme_10.3_11.gif" WIDTH=501 HEIGHT=186 ALT=""></TD>
  </TR>
</TABLE>


</td>
    <td rowspan="3">&nbsp;</td>

  </tr>
  <tr> 
    <td background="img/tabelle_mitte.gif" valign="top" width="501"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td width="20" rowspan="2">&nbsp;</td>
          <td height="15"> 
            <p>&nbsp;</p>
          </td>
          <td width="20" rowspan="2">&nbsp;</td>
        </tr>

        <tr> 
          <td class="text">
<table border="0" cellspacing="0" cellpadding="0">
              <tr valign="top"> 
                <td width="214" class="text"> 
                  <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body>
<table><td width="214" class="text"> 
                    <table width="100%" border="0" cellspacing="0" cellpadding="4">
 					<tr>
                    <td bgcolor="#E8E8E8"><b>:NEWS</b></td>
					</tr>
					</table>
                  
      <p> 
        

<!-- Generated by newsPHP -->
<!-- http://www.nphp.net/ -->

<font color="#606760" size="2"><B></B><BR>
<font color="#606760" size="2"><NewsDate><B>katzencontent</B></font><BR>
<font size="1">seit heute hat diese seite offiziell das <a href="http://disturbed-reality.de/data//katzenblogs.jpg">"cat-content kriterium"</a> erfüllt, deshalb präsentieren wir uns ab sofort mit diesem gütesiegel:<BR><img src="http://disturbed-reality.de/data//catcontent.gif" border="0" alt="" /></font><p>

<font color="#606760" size="2"><B></B><BR>
<font color="#606760" size="2"><NewsDate><B>eigentlich....</B></font><BR>
<font size="1">nunja, man kennt das ja mit diesem eigentlich. eigentlich sollte es ein ganz normaler abend werden. ein videoabend um genauer zu sein. <BR><BR>uneigentlich kam schon um 6 uhr ein sturtztrunkener feuerwehrmann auf allen vieren aus dem garten. und anschliessend nahm das verhängnis seinen lauf...<BR><BR><BR><a href="http://home.arcor.de/bender213/chaosparty_pfingsten_web/"><BR><img src="http://home.arcor.de/bender213/chaosparty_pfingsten_web/images/chaosparty%20pfingsten%20043.jpg" width="211"><BR><BR>zu den fotos<BR></a><BR><BR><BR></font><p>

<font color="#606760" size="2"><NewsDate><B>nachtrag</B></font><BR>
<font size="1">eben ist mir aufgefallen das ich diese fotos hier zwar bei einer der letzten grillaktionen gemacht, aber noch nicht hochgeladen hatte. wurde hiermit nachgeholt! <a href="http://home.arcor.de/bender213/grillen_web/"><BR><img src="http://home.arcor.de/bender213/grillen_web/images/grillen%20033.jpg" width="211"><BR><BR>link</a><BR></font><p>

        <br>
      </p></td></table>
</body>
</html>
				  </td>
    <td width="20">&nbsp;</td>

                <td class="text" width="214"> 
                   
                    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body>
<table><td width="214" class="text"> 
                    <table width="100%" border="0" cellspacing="0" cellpadding="4">
 					<tr>
                    
          <td bgcolor="#E8E8E8"><b>:BLOG</b></td>
					</tr>
					</table>
                  <p>
                    <?xml version="1.0" encoding="iso-8859-1"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!-- layout credits goto http://bluerobot.com/web/layouts/layout2.html -->

<head>
<title>::blog.bist-du-bloe.de::</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta content="TRUE" name="MSSmartTagsPreventParsing" />
</head>
<body>
<font color="#606760" size="2">
<div align="left">
  <!-- // b2 loop start -->
  
    <h1>10.10.04</h1>  <a name="263"></a>  </div>
<div align="left" class="storyTitle">
  <b>und dann kam es endlich...</b><br>
  <!--<a href="?cat=1" title="category: liebes tagebuch...."> -->
  <span class="storyCategory"> 
  liebes tagebuch....  </span></a><br>
  <span class="storyAuthor"> 
  nbkdnzr  </span> um 
  <!-- <a href="index.php?p=263">  -->
  20:32:56  </a></div>
<div align="left" class="storyContent">
  <font size="1">
  hat zwar ewig gedauert, aber es ist da und es ist noch besser als ich es mir ertr&#228;umt hatte-mein ibook!<br />
<br />
der umstieg von windows zum mac ist recht einfach-am anfang verwirrt dich zwar noch alles, aber es ist alles so sch&#246;n aufgebaut das man sich wunderbar schnell einf&#252;hlt. und als k&#246;nung ist mein icq jetzt eine kleine quakende ente :o)<br />
<br />
ich bin grade zu m&#252;de um weiter zu schreiben da ich das we auf unserer landesversammlung war und dezent wenig schlaf abbekommen habe.<br />
<br />
so long and thanks for the fish...  


<a href="#" onClick="javascript: window.open('../b2/index.php?p=263&amp;c=1#comments','commentare','width=520,height=600,scrollbars=yes');" >

  <br>
  kommentieren...

  </a><br>

 
  <hr align="left">
    </div></font>
<div align="left">
  <!-- // this is just the end of the motor - don't touch that line either :) -->
    <h1>07.10.04</h1>  <a name="262"></a>  </div>
<div align="left" class="storyTitle">
  <b>Christoph Maria Herbst</b><br>
  <!--<a href="?cat=1" title="category: liebes tagebuch...."> -->
  <span class="storyCategory"> 
  liebes tagebuch....  </span></a><br>
  <span class="storyAuthor"> 
  nbkdnzr  </span> um 
  <!-- <a href="index.php?p=262">  -->
  20:34:10  </a></div>
<div align="left" class="storyContent">
  <font size="1">
  gestern zu gast in anke late night mit einer absolut herrlichen harald schmidt parodie. versenkt! <a href="http://ankelatenight.sat1.de/archiv/data/0069/0069-00-03-wm_midband.html">schauts euch an....</a>  


<a href="#" onClick="javascript: window.open('../b2/index.php?p=262&amp;c=1#comments','commentare','width=520,height=600,scrollbars=yes');" >

  <br>
  kommentieren...

  </a><br>

 
  <hr align="left">
    </div></font>
<div align="left">
  <!-- // this is just the end of the motor - don't touch that line either :) -->
    <h1>06.10.04</h1>  <a name="261"></a>  </div>
<div align="left" class="storyTitle">
  <b>ohne worte</b><br>
  <!--<a href="?cat=1" title="category: liebes tagebuch...."> -->
  <span class="storyCategory"> 
  liebes tagebuch....  </span></a><br>
  <span class="storyAuthor"> 
  alo  </span> um 
  <!-- <a href="index.php?p=261">  -->
  14:44:22  </a></div>
<div align="left" class="storyContent">
  <font size="1">
  das:<img src="http://www.bundestag.de/mdb15/mdbjpg/m/miersja0.jpeg" width="211" border="0" alt="" /> ist <a href="http://www.bundestag.de/mdb15/bio/m/miersja0.html">Jakob Maria Mierscheid</a>. Jakob ist in der SPD, und weil das so ein wichtiger Verein ist, sitzt er f&#252;r sie im Bundestag. <br />
Jedenfalls behauptet er das. Andere sagen das stimmt gar nicht - er sei ein Phantom und nie da. Das findet Jakob nat&#252;rlich nicht so toll und hat deshalb ein paar ganz wichtige S&#228;tze geschrieben, denn das machen so wichtige M&#228;nner wie er eben so. Einige davon hat mir besonders gut gefallen, und deshalb hab ich ihn f&#252;r euch aufgeschrieben:<br />
<br />
<i>"Ich bin kein Phantom, wie mir manchmal nachgesagt wird, ich bin auch kein<br />
Ph&#228;nomen, man sagt, ich sei einfach ph&#228;nomenal. Wie der Verfassungsjurist<br />
Friedrich Nagelmann und der Berufsdiplomat Edmund F. Dr&#228;cker, meine Kollegen<br />
bei der Judikative und bei der Exekutive, mit denen ich gern zusammenarbeite<br />
geh&#246;re ich zu den S&#228;ulen unseres Staatswesens.<br />
Ich bin Sozialdemokrat, komme aus dem linksrheinischen Hunsr&#252;ck und bin seit<br />
1979 im Bundestag t&#228;tig.<br />
Ich bin weder eine Erfindung, noch ein Patent, ich bin die L&#246;sung.</i><br />
danke Jakob-bitte erl&#246;se uns!<br />
<br />
<br />
Jakob sitzt &#252;brigens seit 1979 im Bundestag und alle Informationen die ich hier geschrieben habe kommen von ebendieser Seite<br />
<a href="http://www.bundestag.de/mdb15/bio/m/miersja0.html">Jakobs Seite beim Bundestag</a><br />
<a href="http://www.bundestag.de/mdbhome/miersja0/ich_ueber_mich.pdf">Jakob &#252;ber sich selbst(pdf)</a><br />
  


<a href="#" onClick="javascript: window.open('../b2/index.php?p=261&amp;c=1#comments','commentare','width=520,height=600,scrollbars=yes');" >

  <br>
  kommentieren...

  </a><br>

 
  <hr align="left">
    </div></font>
<div align="left">
  <!-- // this is just the end of the motor - don't touch that line either :) -->
    <a href="http://disturbed-reality.de/b2/b2login.php" target="_blank"><br />
  login<br />
  </a> 
  <!-- BlueRobot was here. -->
  <br />
  <br />
  </div>
</font>  
</body>
</html>

 
                  </p></td></table>
</body>
</html>
                  
                  </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr> 
    <td height="20" background="layout/tabelle_mitte.gif"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0">

        <tr> 
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td class="menue_top" width="20"> 
            <div align="center">^</div>
          </td>
          <td width="20">&nbsp;</td>
        </tr>

        <tr> 
          <td bgcolor="#A0A0A0" width="5">&nbsp;</td>
          <td bgcolor="#A0A0A0" class="menue_unten">:bist-du-bloe.de v.X.4</td>
          <td bgcolor="#A0A0A0" class="menue_unten">
<div align="center">
<font color="B0B0B0">
<script language="JavaScript" src="http://m1.nedstatbasic.net/basic.js">
</script>
<script language="JavaScript">
<!--
  nedstatbasic("ABoDTwfIAjdLgzdwSlOkjJAiAw4w", 0);
// -->
</script>
</font></div></td>
          <td class="menue_top" height="20" bgcolor="#A0A0A0">&nbsp;</td>
          <td bgcolor="#A0A0A0" width="20" class="menue_unten" align="center"> 
            <div align="center"><a class="menue_unten" href="impressum.html"><b>i</b></a> 
            </div>

          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
